name: gestaocompras_api

services:
  postgresql_gestaocompras:
    image: postgres
    container_name: postgresql_gestaocompras
    cpus: "0.5"
    mem_limit: "256m"
    restart: on-failure:3
    environment:
      POSTGRES_USER: gestaocompras_user
      POSTGRES_PASSWORD: VatvQlFfSpFnevWEThjA
      POSTGRES_DB: gestaocompras_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432"
    networks:
      - backend_gestaocompras
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata/

  gestaocompras_api:
    image: mesaderei/gestaocompras_api:1.0.0
    restart: on-failure:3
    container_name: gestaocompras_api
    ports:
      - 30497:8081
    volumes:
      - api_log_data:/opt/api/logs
      - api_cert_data:/home/app/.aspnet/https
    networks:
      - backend_gestaocompras
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qRbiLME800JZqg40GleK
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/GestaoCompras.API.pfx
      - LOG_DIR=/opt/api/logs
    depends_on:
      - postgresql

  pgadmin_gestaocompras:
    image: dpage/pgadmin4
    cpus: "0.5"
    mem_limit: "256m"
    restart: on-failure:3
    container_name: pgadmin_gestaocompras
    environment:
      PGADMIN_DEFAULT_EMAIL: gabrielsrios1106@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Ga110600
    ports:
      - 8090:80
    networks:
      - backend_gestaocompras
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql

networks:
  backend_gestaocompras:
    driver: bridge

volumes:
  pg_data:
  api_log_data:
  api_cert_data:
    external: true
  pgadmin_data: